### ISSUE TITLE
Readme example not working

### ISSUE THREAD

**Issue by avivajpeyi** [gwastro/2-ogc#5]
It seems like the example in the README.md is not working:

```python
Python 3.7.6 (default, Jan  8 2020, 13:42:34)
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import h5py
>>>
>>> catalog = h5py.File('./2-OGC.hdf', 'r')
>>>
>>> # Get a numpy structured array of the candidate event properties.
>>> all_candidates = catalog['complete']
>>> bbh_candidates = catalog['bbh']
>>>
>>> # Accessing a column by name
>>> ranking_values = all_candidates['stat']
>>>
>>> # Selecting parts of the catalog
>>> region = all_candidates['mass1'] + all_candidates['mass2'] < 4
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unsupported operand type(s) for +: 'Dataset' and 'Dataset'
>>> lowmass_candidates = all_candidates[region]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'region' is not defined
>>>
```

**Comment by ahnitz** [comment]
@avivajpeyi Ah, thanks, yes, I believe I forgot to include '[:]' here. 

So it should be 
```
region = all_candidates['mass1'][:] + all_candidates['mass2'][:] < 4
```

Does that resolve your issue?

**Comment by ahnitz** [comment]
So the following should work. 
```
import h5py

catalog = h5py.File('./2-OGC.hdf', 'r')

# Get a numpy structured array of the candidate event properties.
all_candidates = catalog['complete']
bbh_candidates = catalog['bbh']

# Accessing a column by name
ranking_values = all_candidates['stat'][:]

# Selecting parts of the catalog
region = all_candidates['mass1'][:] + all_candidates['mass2'][:] < 4
lowmass_snr = all_candidates['H1_SNR'][:][region]
```

**Comment by avivajpeyi** [comment]
Thanks!
